futonshinkurenpa:
  icon: diamond_axe:190
  icon_disabled: diamond_hoe:190
  icon_url: http://textures.minecraft.net/texture/7134aed98232d9946f9dbd738a37e68f36a9a773a863dde206bb9115b993d78
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: Damage
      - class: AreaOfEffect
        radius: 7
        actions:
        - class: VelocityAction
          y_offset: 0.5
        - class: Damage
          damage: 2
  effects:
    hit_entity:
    - class: EffectSingle
      sound: entity.ender_dragon.flap
      sound_volume: 1.3
      sound_pitch: 0.1
      location: target
      particle: explosion_large
      particle_count: 4
      particle_offset_y: 3
      particle_offset_x: 3
      particle_offset_z: 3
    cast:
    - class: EffectSingle
      sound: entity.ender_dragon.flap
      sound_pitch: 1.5
      location: origin
      color_override: color
      effectlib:
        class: ConeEffect
        iterations: 10
        particle: redstone
        color: FFFFFF
        lengthGrow: 0.5
        radiusGrow: 0.03
        updateLocations: false
        updateDirections: false
    tick:
    - particle: cloud
      location: target
      particle_offset_y: 2
      particle_count: 8
    hit:
    - class: EffectSingle
      sound: magic.zap_crack
      sound_volume: 0.2
      location: target
      particle: explosion_large
  parameters:
    hitbox_size: 3
    allow_max_range: true
    velocity: 44
    range: 42
    target_count: 100
    item_speed: 0.1
    living_entity_speed: 1
    z_offset: 0.75
    hitbox: true
    target_type: Entity
    damage: 8
    cooldown: 800
    reorient: false
  costs:
    mana: 40
