raitonraikage:
  icon: diamond_axe:72
  icon_disabled: diamond_hoe:72
  icon_url: http://textures.minecraft.net/texture/6b7da98ef45cf45185d21d61f5fa3d5966a3ee52273620a6e4dfd54cf99dbc
  actions:
    cast:
    - class: PotionEffect
    - class: Repeat
      repeat: 24
      actions:
      - class: Delay
        delay: 250
      - class: PlayEffects
        effects: bloodsound
  effects:
    cast:
    - class: EffectSingle
      sound: magic.electrify
      sound_pitch: 1.3
      sound_volume: 0.3
      location: origin
      source_location: body
      effectlib:
        class: Modified
        duration: 8000
        parameters:
          radius: sin(t/5)*0.3
        effect:
          class: Sphere
          particle: redstone
          color: "4169e1"
          particles: 4
          particle_count: 5
          particle_offset_x: 1
          particle_offset_y: 1
          particle_offset_z: 1
    - class: EffectSingle
      location: origin
      source_location: body
      effectlib:
        class: Modified
        duration: 8000
        parameters:
          radius: sin(t/5)*0.2
        effect:
          class: Sphere
          particle: end_rod
          particles: 2
          particle_count: 1
          particle_offset_x: 1
          particle_offset_y: 1
          particle_offset_z: 1
    bloodsound:
    - class: EffectSingle
      sound: magic.electrify
      sound_pitch: 1.3
      sound_volume: 0.1
  parameters:
    effect_speed: 10
    effect_increase_damage: 1
    duration: 8000
    target_type: Player
    target: self
