raitonhebiikazuchi:
  icon: diamond_axe:145
  icon_disabled: spell_icon_disabled:145
  icon_url: http://textures.minecraft.net/texture/1e5b76818c576079939b5a4b033ddfb5c2364fc9f764e573c59508b811e365
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: Damage
      - class: Delay
      - class: AreaOfEffect
        actions:
        - class: Asynchronous
          actions:
          - class: CustomProjectile
            velocity: 150
            actions:
            - class: Repeat
              actions:
              - class: Electrify
              - class: Damage
                player_damage: 0.5
                entity_damage: 1
              - class: Delay
      - class: Electrify
      - class: Repeat
        actions:
        - class: Damage
        - class: Delay
  effects:
    cast:
    - class: EffectSingle
      sound: magic.zap
      sound_volume: 0.3
      sound_pitch: 0.9
      location: origin
    - class: EffectSingle
      sound: magic.electrify
      sound_volume: 1
      sound_pitch: 0.8
      location: origin
    projectile:
    - class: EffectSingle
      effectlib:
        class: DnaEffect
        particleHelix: fireworks_spark
        iterations: 100
        particleBase1: redstone
        color_base1: "ffff00"
        particle_base2: redstone
        color_base2: "ffd700"
    - location: source
      effectlib:
        class: LineEffect
        isZigZag: true
        zigZags: 4
        zigZagOffset: 0,0.2,0
        length: 20
        particles: 20
        particle: redstone
        color: "ffff00"
        particle_count: 4
        particle_offset_x: 0.1
        particle_offset_y: 0.1
        particle_offset_z: 0.1
        duration: 2000
    tick:
    - particle: fireworks_spark
      particle_count: 2
      particle_offset_x: 0.1
      particle_offset_y: 0.1
      particle_offset_z: 0.1
      location: target
    hit:
    - class: EffectSingle
      location: target
      particle: end_rod
      particle_count: 10
      particle_offset_x: 1
      particle_offset_y: 1
      particle_offset_z: 1
    hit_entity:
    - class: EffectSingle
      sound: magic.electrify
      sound_volume: 0.5
      sound_pitch: 1.4
      location: target
    - class: EffectSingle
      sound: magic.zap
      sound_volume: 0.8
      sound_pitch: 0.7
      location: target
  parameters:
    tick_size: 5
    target: other
    target_self: false
    target_source: false
    range: 32
    velocity: 40
    radius: 3
    target_count: 3
    target_type: Damageable
    damage: 6
    delay: 250
    repeat: 2
    target_breakables: 1
    cooldown: 1400
  costs:
    mana: 35
