yotondefenseelastique:
  icon: diamond_axe:139
  icon_disabled: diamond_hoe:139
  actions:
    cast:
    - class: Asynchronous
      actions:
      - class: ChangeContext
        source_yaw_offset: 15
        actions:
        - class: CustomProjectile
          tick:
          - class: Sphere
            y_size: 1.5
            z_size: 3.7
            x_size: 3.7
            orient: true
            reorient: false
            actions:
            - class: ModifyBlock
              ignore_result: true
            - class: Undo
              ignore_result: true
            - class: AreaOfEffect
              actions:
              - class: Damage
              - class: PlayEffects
                effect: waterballhit
                ignore_result: true
              - class: Velocity
                speed: 0.1
    - class: Asynchronous
      actions:
      - class: ChangeContext
        source_yaw_offset: -15
        actions:
        - class: CustomProjectile
          tick:
          - class: Sphere
            y_size: 1.5
            z_size: 3.7
            x_size: 3.7
            orient: true
            reorient: false
            actions:
            - class: ModifyBlock
              ignore_result: true
            - class: Undo
              ignore_result: true
            - class: AreaOfEffect
              actions:
              - class: Damage
              - class: PlayEffects
                effect: waterballhit
                ignore_result: true
              - class: Velocity
                speed: 0.1
    - class: Asynchronous
      actions:
      - class: CustomProjectile
        tick:
        - class: Sphere
          y_size: 1.5
          z_size: 3.7
          x_size: 3.7
          orient: true
          reorient: false
          actions:
          - class: ModifyBlock
            ignore_result: true
          - class: Undo
            ignore_result: true
          - class: AreaOfEffect
            actions:
            - class: Damage
            - class: PlayEffects
              effect: waterballhit
              ignore_result: true
            - class: Velocity
              speed: 0.1
  effects:
    cast:
    - class: EffectSingle
      sound: entity.boat.paddle_water
      sound_pitch: 1.4
      sound_volume: 1
    waterballhit:
    - class: EffectSingle
    - location: target
      effectlib:
        class: SphereEffect
        iterations: 4
        particle: bubble_pop
        radius: 1.4
        particles: 1
        speed: 0.1
        y_offset: -0.5
    tick:
    - class: EffectSingle
      sound: entity.boat.paddle_water
      sound_pitch: 0.1
      sound_volume: 1
    projectile:
    - location: origin
      effectlib:
        class: Sphere
        particle: drip_lava
        radius: 2
        particles: 80
  parameters:
    range: 24
    destructible: destructible_replace
    undo: 3700
    target: none
    target_type: Damageable
    transparent: orange_terracotta,air,dirt,stone,grass,gravel,andesite,diorite,granite,cobblestone,sand,sandstone,tallgrass,destructible,water
    radius: 2
    velocity: 8
    undo_speed: 400
    cooldown: 1400
    brush: stained_hardened_clay:1
    damage: 1
    undo_to: 4000
    start: 6
  costs:
    mana: 50
