
#standartkenjutsu

chakraslash:
  name: Разрез Ударной Волны Чакры
  icon: diamond_axe:178
  icon_disabled: diamond_hoe:178
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: kenjutsu
  worth: 100
  earns_sp: 8
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
    - class: Sphere
      actions:
      - class: BreakBlock
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - requires_entity_target: true
      effectlib:
        class: Equation
        iterations: 50
        particles: 20
        particle: drip_lava
        particle_count: 20
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: origin
      effectlib:
        class: Equation
        iterations: 50
        particles: 20
        particle: sweep_attack
        xEquation: '1.2'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: origin
      effectlib:
        class: Sphere
        particle: cloud
        speed: 1
        iterations: 2
  parameters:
    target_type: Damageable
    living_entity_speed: 2.5
    allow_max_range: false
    range: 5
    hitbox: false
    fov: 0.4
    damage: 10
    target_breakables: 1
    cooldown: 5000
    magic_damage: false
    instant_block_effects: true
    undo: 15000
    radius: 1
  costs:
    mana: 0



heavencutter:
  name: Разрез Ударной Волны Чакры
  icon: diamond_axe:178
  icon_disabled: diamond_hoe:178
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: kenjutsu
  worth: 100
  earns_sp: 8
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
    - class: Sphere
      actions:
      - class: BreakBlock
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - requires_entity_target: true
      effectlib:
        class: Equation
        iterations: 50
        particles: 20
        particle: drip_lava
        particle_count: 20
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: target
      effectlib:
        class: Sphere
        particle: sweep_attack
        speed: 1
        iterations: 2
    - location: target
      effectlib:
        class: SkyRocket
        power: 1.3
  parameters:
    target_type: Damageable
    living_entity_speed: 1.5
    allow_max_range: false
    range: 5
    hitbox: false
    fov: 0.4
    damage: 5
    target_breakables: 1
    cooldown: 5000
    magic_damage: false
    instant_block_effects: true
    undo: 15000
    radius: 1
  costs:
    mana: 0



moonlight:
  name: Лунный Свет
  icon: diamond_axe:178
  icon_disabled: diamond_hoe:178
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: kenjutsu
  worth: 100
  earns_sp: 8
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
    - class: Sphere
      actions:
      - class: BreakBlock
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - requires_entity_target: true
      effectlib:
        class: Equation
        iterations: 5
        particles: 10
        particle: drip_lava
        particle_count: 10
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: cloud
        size: 0.3
    - effectlib:
        class: Equation
        iterations: 5
        particles: 10
        particle: sweep_attack
        particle_count: 10
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      effectlib:
        class: Sphere
        particle: cloud
        speed: 1.5
        iterations: 1
  parameters:
    target_type: Damageable
    living_entity_speed: 4
    allow_max_range: false
    range: 5
    hitbox: false
    fov: 0.4
    damage: 6
    target_breakables: 1
    cooldown: 5000
    magic_damage: false
    instant_block_effects: true
    undo: 15000
    radius: 1
  costs:
    mana: 0


crescentmoonlight:
  name: Лезвие Полумесяца
  icon: diamond_axe:178
  icon_disabled: diamond_hoe:178
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: kenjutsu
  worth: 100
  earns_sp: 8
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
    - class: Sphere
      actions:
      - class: BreakBlock
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - requires_entity_target: true
      effectlib:
        class: Equation
        iterations: 5
        particles: 10
        particle: drip_lava
        particle_count: 10
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: cloud
        size: 0.3
    - effectlib:
        class: Equation
        iterations: 5
        particles: 10
        particle: sweep_attack
        particle_count: 10
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - effectlib:
        class: Equation
        iterations: 50
        particles: 20
        particle: end_rod
        particle_count: 20
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      effectlib:
        class: Sphere
        particle: cloud
        speed: 1.5
        iterations: 3
  parameters:
    target_type: Damageable
    living_entity_speed: 10
    allow_max_range: false
    break_durability: 15
    destructible: solid
    range: 5
    hitbox: false
    fov: 0.4
    damage: 15
    target_breakables: 1
    cooldown: 5000
    magic_damage: false
    instant_block_effects: true
    undo: 15000
    radius: 2
  costs:
    mana: 0


chakraflash:
  name: Вспышка
  icon: diamond_axe:178
  icon_disabled: diamond_hoe:178
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: kenjutsu
  worth: 100
  earns_sp: 8
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
    - class: Sphere
      actions:
      - class: BreakBlock
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - requires_entity_target: true
      effectlib:
        class: Equation
        iterations: 5
        particles: 10
        particle: drip_lava
        particle_count: 10
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: crit_magic
        size: 0.3
    - location: target
      effectlib:
        class: Sphere
        particle: sweep_attack
        speed: 1
        iterations: 2
    - effectlib:
        class: Equation
        iterations: 80
        particles: 20
        particle: crit_magic
        particle_count: 20
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      effectlib:
        class: Sphere
        particle: crit_magic
        speed: 1.5
        iterations: 3
  parameters:
    target_type: Damageable
    living_entity_speed: 10
    allow_max_range: false
    range: 5
    radius: 2
    hitbox: false
    fov: 0.4
    damage: 15
    undo: 15000
    target_breakables: 1
    break_durability: 20
    cooldown: 5000
    destructible: solid
    magic_damage: false
    instant_block_effects: true
  costs:
    mana: 0


samuraistrength:
  name: Усиление Самурая
  description:
  icon: diamond_pickaxe:150
  icon_disabled: diamond_axe:150
  icon_url: http://textures.minecraft.net/texture/15987e49e7ed16df536f4dbf685e7720b88b4de6deaf614d84ab9f9884725c
  alias: perk
  category: kenjutsu
  worth: 220
  earns_sp: 0
  upgrade_required_path: beginner
  upgrade_required_casts: 40
  quick_cast: true
  toggle: cancel
  disable_mana_regeneration: true
  actions:
    cast:
    - class: Deactivate
    - class: Command
    - class: Repeat
      actions:
      - class: PotionEffect
        duration: 1500
      - class: Delay
        delay: 1000
  effects:
    cast:
    - sound: entity_experience_orb_pickup
  parameters:
    target: self
    effect_increase_damage: 3
    cooldown: 100
    cancel_on_death: true
    repeat: infinite
  costs:
    xp: 10
  active_costs:
    xp: 1

