
#HATAKE CLAN


#https://naruto.fandom.com/ru/wiki/Клинок_Чакры_Белого_Света
hatakewound:
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: hiden
  worth: 0
  earns_sp: 0
  actions:
    cast:
    - class: Damage
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - requires_entity_target: true
      effectlib:
        class: Equation
        iterations: 50
        particles: 20
        particle: drip_lava
        particle_count: 20
        particle_offset_x: 0
        particle_offset_y: 0.1
        particle_offset_z: 0
        xEquation: '1.5'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: source
      material: redstone_block
      effectlib:
        class: Equation
        iterations: 50
        particles: 20
        particle: end_rod
        color: FFFFFF
        xEquation: '1.2'
        yEquation: -t/20 + 0.5
        zEquation: -t/20 + 0.5
        updateLocations: false
        updateDirections: false
  parameters:
    target_type: Damageable
    allow_max_range: false
    range: 5
    hitbox: false
    fov: 0.4
    damage: 5
    target_breakables: 1
    cooldown: 200
    magic_damage: false
    instant_block_effects: true
  costs:
    mana: 0
