
#JUGO CLAN

#https://naruto.fandom.com/ru/wiki/Цепь
jugoarm:
  name: Цепь
  description: Заставляет вашу руку растянуться для удара
  icon: diamond_pickaxe:67
  icon_disabled: diamond_axe:67
  icon_url: http://textures.minecraft.net/texture/5d9ddb39f5cd587f63bb175dfaf55baaa917c1a2a3ca987a18d90c9e1a578d
  category: hiden
  pvp_restricted: true
  worth: 10
  actions:
    cast:
    - class: Line
      actions:
      - class: ModifyBlock
    - class: Damage
  effects:
    cast:
    - class: EffectSingle
      sound: block_grass_step
    iterate:
    - class: EffectSingle
      particle: block_crack
      location: target
  parameters:
    target_type: Damageable
    transparent: transparent_to_construction
    allow_max_range: true
    range: 16
    size: 16
    increment_data: false
    undo: 4000
    brush: stained_clay:9
    player_damage: 10
    entity_damage: 10
    destructible: destructible_replace
  costs:
    mana: 20







#https://naruto.fandom.com/ru/wiki/Уничтожающий_Кулак-Топор
jugosword:
  name: Уничтожающий Кулак-Топор
  description: Удар топором, образованным из вашей руки
  icon: diamond_pickaxe:65
  icon_disabled: diamond_axe:65
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: hiden
  worth: 20
  earns_sp: 0
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: target
      requires_entity_target: true
      material: redstone_block
      effectlib:
        class: Sphere
        particle: redstone
        color: 808080
        particles: 20
        particle_count: 20
        iterations: 8
        radius: 0.1
    - location: source
      material: redstone_block
      effectlib:
        class: Cylinder
        particle: redstone
        color: 808080
        particles: 40
        particle_count: 40
        iterations: 20
        height: 1.5
        radius: 0.2
  parameters:
    target_type: Damageable
    allow_max_range: false
    range: 5
    living_entity_speed: 1
    hitbox: false
    fov: 0.4
    damage: 10
    target_breakables: 1
    cooldown: 1000
    magic_damage: false
    instant_block_effects: true
  costs:
    mana: 10









#https://naruto.fandom.com/ru/wiki/Трансформация_Мудреца
jugomod:
  name: Трансформация Мудреца
  description: Режим, аналогичный Режиму Мудреца
  icon: diamond_pickaxe:68
  icon_disabled: diamond_axe:68
  icon_url: http://textures.minecraft.net/texture/15987e49e7ed16df536f4dbf685e7720b88b4de6deaf614d84ab9f9884725c
  alias: perk
  category: hiden
  worth: 50
  earns_sp: 0
  upgrade_required_path: beginner
  upgrade_required_casts: 40
  quick_cast: true
  toggle: cancel
  disable_mana_regeneration: true
  actions:
    cast:
    - class: Repeat
      actions:
      - class: PotionEffect
        duration: 5000
      - class: Delay
        delay: 1000
  effects:
    cast:
    - sound: entity_experience_orb_pickup
    - location: origin
      sound: entity_wither_break_block
      sound_pitch: 0.8
      source_location: body
      effectlib:
        class: Modified
        duration: 4000
        parameters:
          size: (1 - (t / i)) * 1.5 + 0.5
        effect:
          class: AnimatedBall
          particle: villager_happy
          color: 663300
          particle_count: 1
          particle_offset_x: 0.05
          particle_offset_y: -1
          particle_offset_z: 0.05
          particle_size: 2
          y_factor: 0
  parameters:
    target: self
    effect_speed: 5
    effect_jump: 5
    effect_damage_resistance: 2
    effect_increase_damage: 3
    cooldown_reduction: 0.2
    cooldown: 6000
    cancel_on_death: true
    repeat: infinite
    duration: 360000
  costs:
    mana: 20
  active_costs:
    mana: 5



#https://naruto.fandom.com/ru/wiki/Поглощение_Клеточной_Регенерации
jugoheal:
  name: Поглощение Клеточной Регенерации
  description: Забирает у жертвы её жизненные силы, восстанавливая себя
  icon: diamond_pickaxe:66
  icon_disabled: diamond_axe:66
  upgrade_required_path: apprentice
  upgrade_required_casts: 50
  icon_url: http://textures.minecraft.net/texture/df4396a2bc47bc4dd545fc787a3ad8a0a75b8783cb5d81482c2016fab9cd2a
  category: hiden
  worth: 30
  earns_sp: 0
  actions:
    cast:
    - class: Damage
    - class: VelocityAction
  effects:
    cast:
    - class: EffectSingle
      requires_entity_target: true
      location: target
      color: 8A0829
      source_location: body
      effectlib:
        class: BleedEffect
        iterations: 4
        hurt: false
        offset: 0,-1,0
    - class: EffectSingle
      sound: magic.crack
      sound_volume: 1
      particle: sweep_attack
      particle_count: 5
      particle_offset_x: 0.2
      particle_offset_y: 0.05
      particle_offset_z: 0.2
      relative_offset: 2,0,0
    - location: target
      requires_entity_target: true
      use_hit_location: false
      use_wand_location: false
      target_offset: 0,-1.3,0
      effectlib:
        class: AnimatedBall
        duration: 2000
        particle: item_crack
        material: redstone
        size: 0.3
    - location: target
      requires_entity_target: true
      material: redstone_block
      effectlib:
        class: Sphere
        particle: redstone
        color: 808080
        particles: 20
        particle_count: 20
        iterations: 8
        radius: 0.1
    - location: source
      material: redstone_block
      effectlib:
        class: Cylinder
        particle: redstone
        color: 808080
        particles: 40
        particle_count: 40
        iterations: 20
        height: 1.5
        radius: 0.2
  parameters:
    target_type: Damageable
    allow_max_range: false
    range: 5
    living_entity_speed: 1
    hitbox: false
    fov: 0.4
    damage: 10
    target_breakables: 1
    cooldown: 1000
    magic_damage: false
    instant_block_effects: true
  costs:
    mana: 10




