
#YAMANAKA

#https://naruto.fandom.com/ru/wiki/Техника_Нарушения_Сознания_Тела
mindbreak:
  name: Принуждение Шарингана
  description: Техника, которая используется, чтобы обездвижить противника, заключив его внутрь водяной сферы
  icon: diamond_pickaxe:108
  icon_disabled: diamond_axe:108
  icon_url: http://textures.minecraft.net/texture/2ba95570c7b712713632d4c0d2fc66906613d3850a596a0267c6d763fe741ac
  upgrade_required_path: beginner
  upgrade_required_casts: 20
  category: hiden
  worth: 10
  earns_sp: 0
  earns_cooldown: 10000
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: AreaOfEffect
        actions:
        - class: PotionEffect
          ignore_result: true
  effects:
    cast:
    - class: EffectSingle
      sound: magic.zap_crack
      location: origin
    tick:
    - effectlib:
        class: Sphere
        speed: 1
        particle: spell_mob
        color: 280000
        iterations: 2
        particle_count: 5
        particles: 1
        particle_offset_y: 0.2
        particle_offset_x: 0.2
        particle_offset_z: 0.2
        particle_size: 1
      location: target
    hit:
    - location: target
      sound: entity_wither_break_block
      sound_pitch: 0.8
      source_location: body
      effectlib:
        class: Sphere
        speed: 1
        particle: spell_mob
        iterations: 5
        color: 280000
  headshot_parameters:
    damage_multiplier: 1.5
  parameters:
    allow_max_range: true
    velocity: 200
    range: 24
    hitbox: true
    target_type: Damageable
    player_damage: 0
    entity_damage: 0
    target_breakables: 1
    cooldown: 1000
    reorient: false
    damage: 0
    radius: 2
    potion_effects:
      slow: 250
      jump: 250
      weakness: 100
      duration: 10000
    duration: 10000
  costs:
    mana: 50

#sensor broadcast (/broadcast)!!!!





mindtransfer:
  icon: diamond_pickaxe:92
  icon_disabled: diamond_axe:92
  icon_url: http://textures.minecraft.net/texture/c7142a19d8c84389da74b69641542b8b2fafbed8f7515d1d36c63c96bd749
  category: hiden
  worth: 50
  tags: noduel
  actions:
    cast:
    - class: PotionEffect
    - class: Command
  worth: 1000
  parameters:
    effect_slow: 200
    effect_jump: 250
    effect_weak: 200
    effect_confusion: 200
    effect_slow_digging: 200
    duration: 60000
    commands:
    - cast mindtransferbase
    - cast mindtransferbase2
    target_breakables: 1
    target: self
    range: 24
    item_force: 1
    entity_force: 1
    bypass_backfire: true
  costs:
    mana: 100

mindtransferbase:
  icon: diamond_pickaxe:151
  icon_disabled: diamond_pickaxe:151
  icon_url: http://textures.minecraft.net/texture/c7142a19d8c84389da74b69641542b8b2fafbed8f7515d1d36c63c96bd749
  category: hiden
  tags: noduel
  class: ForceSpell
  worth: 1000
  effects:
    cast:
    - class: EffectSingle
      sound: magic.zap_big
      location: origin
      effectlib:
        class: DnaEffect
        particles_base: 0
        particles_helix: 7
        particle_helix: redstone
        particle_base1: redstone
        particle_base2: redstone
        iterations: 10
    target_selected:
    - class: EffectSingle
      location: origin
      sound: magic.hit
      sound_volume: 0.5
    - class: EffectSingle
      location: target
      use_hit_location: false
      effectlib:
        class: StarEffect
        iterations: 4
        particle: redstone
        color: '990000'
        spikeHeight: 1.2
        innerRadius: 0.2
    - class: EffectSingle
      location: target
      use_hit_location: false
      source_location: eyes
      color_override: color
      effectlib:
        class: IconEffect
        iterations: 1000
        particle: redstone
        color: '990000'
        period: 1
        y_offset: 0
        offset: 0,0.7,0
    - class: EffectTrail
      particle: redstone
      color: '990000'
  parameters:
    target_type: LivingEntity
    target_breakables: 1
    target: other_entity
    range: 10
    item_force: 1
    entity_force: 1
    bypass_backfire: true
  costs:
    mana: 100



mindtransferbase2:
  icon: diamond_pickaxe:151
  icon_disabled: diamond_pickaxe:151
  icon_url: http://textures.minecraft.net/texture/c7142a19d8c84389da74b69641542b8b2fafbed8f7515d1d36c63c96bd749
  category: hiden
  tags: noduel
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: PotionEffect
  worth: 1000
  parameters:
    effect_slow: 200
    effect_jump: 250
    effect_weak: 200
    effect_confusion: 200
    effect_slow_digging: 200
    duration: 60000
    target_breakables: 1
    target_type: Player
    target: other
    range: 24
  costs:
    mana: 100




mindcontrol:
  icon: diamond_pickaxe:91
  icon_disabled: diamond_axe:91
  icon_url: http://textures.minecraft.net/texture/c7142a19d8c84389da74b69641542b8b2fafbed8f7515d1d36c63c96bd749
  category: hiden
  tags: noduel
  class: ForceSpell
  worth: 100
  effects:
    cast:
    - class: EffectSingle
      sound: magic.zap_big
      location: origin
      effectlib:
        class: DnaEffect
        particles_base: 0
        particles_helix: 7
        particle_helix: redstone
        particle_base1: redstone
        particle_base2: redstone
        iterations: 10
    target_selected:
    - class: EffectSingle
      location: origin
      sound: magic.hit
      sound_volume: 0.5
    - class: EffectSingle
      location: target
      use_hit_location: false
      effectlib:
        class: StarEffect
        iterations: 4
        particle: redstone
        color: '990000'
        spikeHeight: 1.2
        innerRadius: 0.2
    - class: EffectSingle
      location: target
      use_hit_location: false
      source_location: eyes
      color_override: color
      effectlib:
        class: IconEffect
        iterations: 1000
        particle: redstone
        color: '990000'
        period: 1
        y_offset: 0
        offset: 0,0.7,0
    - class: EffectTrail
      particle: redstone
      color: '990000'
  parameters:
    target_type: LivingEntity
    target_breakables: 1
    target: other_entity
    range: 16
    item_force: 1
    entity_force: 2
    bypass_backfire: true
  costs:
    mana: 100
