#EARTH RELEASE
earth:
  category: basic
  earns_sp: 0
  upgrade_required_path: student
  upgrade_required_casts: 50

#https://naruto.fandom.com/ru/wiki/Стихия_Земли:_Танец_Песка
earthcollapse:
  name: '[lang]magic.spells.basic.earth1.name[/lang]'
  description: '[lang]magic.spells.basic.earth1.description[/lang]'
  alias: earth1
  inherit: earth
  icon: diamond_pickaxe:26
  icon_disabled: diamond_axe:26
  worth: 10
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: Sphere
        actions:
        - class: ModifyBlock
        - class: Damage
  effects:
    cast:
    - class: EffectSingle
      sound: magic.ignite
      sound_volume: 1
      location: origin
      effectlib:
        class: ConeEffect
        iterations: 10
        particle: spell_witch
        lengthGrow: 0.4
    tick:
    - particle: falling_dust
      location: target
      material: obsidian
    hit:
    - class: EffectSingle
      target_offset: 0,0.5,0
      location: target
      color: FFFF00
      firework: burst
    - class: EffectSingle
      location: target
      target_offset: 0,0.5,0
      effectlib:
        class: HelixEffect
        iterations: 1
        radius: 4
        particle: falling_dust
        particle_count: 2
        particle_offset_x: 0.1
        particle_offset_y: 0
        particle_offset_z: 0.1
    undo:
    - class: EffectSingle
      sound: magic.shimmer
      location: target
    undo_block:
    - location: target
      use_block_location: true
      effectlib:
        class: Modified
        period: 2
        iterations: 8
        parameters:
          radius: (1 - (t / i)) * 5 + 0.2
          particles: (t / i) * 40
        effect:
          class: Sphere
          particle: block_crack
          y_offset: 0
          offset: 0,0.7,0
          particle_count: 4
          particle_offset_x: 0.1
          particle_offset_y: 0.1
          particle_offset_z: 0.1
  parameters:
    velocity: 1500
    allow_max_range: false
    range: 16
    brush: sand
    falling: true
    radius: 5
    transparent: transparent_to_construction
    destructible_override: true
    undo: 10000
    cooldown: 8000
    select_self: false
    undo_speed: 1
    damage: 5
  costs:
    mana: 40

#https://naruto.fandom.com/ru/wiki/Стихия_Земли:_Техника_Упрочнения
earthharden:
  name: '[lang]magic.spells.basic.earth2.name[/lang]'
  description: '[lang]magic.spells.basic.earth2.description[/lang]'
  alias: earth2
  inherit: earth
  icon: diamond_pickaxe:25
  icon_disabled: diamond_axe:25
  worth: 20
  actions:
    cast:
    - class: Recurse
      actions:
      - class: ModifyBlock
  effects:
    cast:
    - sound: magic.shimmer
    - class: EffectTrail
      particle: block_crack
      particle_count: 20
      particle_offset_x: 0.2
      particle_offset_y: 0.2
      particle_offset_z: 0.2
    - location: target
      effectlib:
        class: Helix
        particle: block_crack
        particle_count: 8
        particle_offset_x: 0.2
        particle_offset_y: 0.5
        particle_offset_z: 0.2
        iterations: 1
        radius: $size
  parameters:
    allow_max_range: false
    range: 16
    size: 3
    destructible_override: true
    destructible: destructible,hardenable
    brush: coal_block
    transparent: transparent_to_construction
    undo: 4000
    cooldown: 1000
    bypass_backfire: true
    select_self: false
    replace: true
  costs:
    mana: 30

#https://naruto.fandom.com/ru/wiki/Щит_Песка
earthsandshield:
  name: '[lang]magic.spells.basic.earth3.name[/lang]'
  description: '[lang]magic.spells.basic.earth3.description[/lang]'
  alias: earth3
  inherit: earth
  icon: diamond_pickaxe:27
  icon_disabled: diamond_axe:27
  worth: 30
  actions:
    cast:
    - class: CustomProjectile
      actions:
      - class: Sphere
        actions:
        - class: ModifyBlock
  effects:
    cast:
    - class: EffectSingle
      sound: magic.shield
    tick:
    - location: target
      particle: block_crack
      particle_count: 10
      particle_offset_x: 0.2
      particle_offset_y: 0.2
      particle_offset_z: 0.2
    hit:
    - location: target
      effectlib:
        class: SphereEffect
        particle: block_crack
        particle_count: 10
        particles: 5
        particle_offset_x: 0.3
        particle_offset_y: 0.3
        particle_offset_z: 0.3
        radius: $radius
        duration: 2000
  parameters:
    target: self
    allow_max_range: false
    velocity: 50
    target_type: LivingEntity
    range: 32
    thickness: 1
    radius: 4
    type: sphere
    transparent: transparent_to_construction
    destructible: destructible_replace
    check_destructible: true
    undo: 8000
    brush: sandstone
    brushcolor: true
    cooldown: 5000
    breakable: 1
    reflect_chance: 0
    miss_effects: hit
    miss: actions
  costs:
    mana: 50

#https://naruto.fandom.com/ru/wiki/Стихия_Земли:_Техника_Двойного_Самоубийственного_Обезглавливания
underearth:
  name: '[lang]magic.spells.basic.earth4.name[/lang]'
  description: '[lang]magic.spells.basic.earth4.description[/lang]'
  alias: earth4
  inherit: earth
  icon: diamond_pickaxe:24
  icon_disabled: diamond_axe:24
  worth: 40
  actions:
    cast:
    - class: Volume
      ignore_result: true
      actions:
       - class: Cover
         actions:
         - class: ModifyBlock
    - class: Delay
  effects:
    cast:
    - class: EffectSingle
      sound: magic.shimmer_quiet
      sound_volume: 1
      sound_pitch: 0.2
      location: target
      material: stone
      effectlib:
        class: Helix
        offset: 0,-0.5,0
        particle: block_crack
        material: grass
        iterations: 4
        radius: 2
  parameters:
    target: block
    target_type: Entity
    start_at_target: true
    x_size: 1
    y_size: 5
    z_size: 1
    size: 8
    range: 2
    allow_max_range: true
    orient: true
    target_count: 16
    item_speed: 0.4
    living_entity_speed: 0.2
    direction: 0,0,0
    speed: 0.8
    cooldown: 1000
    delay: 250
    brush: air
    falling: false
    undo: 1000
    undo_speed: 100
  costs:
    mana: 60





#https://naruto.fandom.com/ru/wiki/Техника_Разделения_Земли | Мб лучше
#https://naruto.fandom.com/ru/wiki/Стихия_Земли:_Техника_Земляной_Волны
earthwave:
  name: '[lang]magic.spells.basic.earth5.name[/lang]'
  description: '[lang]magic.spells.basic.earth5.description[/lang]'
  alias: earth5
  inherit: earth
  icon: diamond_pickaxe:23
  icon_disabled: diamond_axe:23
  worth: 50
  actions:
    cast:
    - class: Line
      actions:
      - class: PlayEffects
        ignore_result: true
        effects: iterate
      - class: Volume
        ignore_result: true
        actions:
        - class: Cover
          actions:
          - class: ModifyBlock
      - class: AreaOfEffect
        actions:
        - class: Velocity
          ignore_result: true
        - class: Damage
      - class: Delay
  effects:
    cast:
    - class: EffectSingle
      sound: magic.shimmer_quiet
      sound_volume: 1
      sound_pitch: 0.2
      location: origin
      material: stone
      effectlib:
        class: EquationEffect
        xEquation: t/16
        yEquation: sin(t/16)
        zEquation: '0'
        x2Equation: '0'
        y2Equation: '0'
        z2Equation: t2/16 * 4 - 4
        iterations: 8
        particles: 24
        particles2: 32
        particle: block_crack
        orient: true
        orientPitch: false
        period: 6
    iterate:
    - class: EffectSingle
      location: target
      sound: magic.shimmer_quiet
      orient: true
      effectlib:
        class: EquationEffect
        xEquation: '0'
        yEquation: floor(t/16)*0.2-1
        zEquation: t/16*4-4
        iterations: 2
        particles: 16
        particle_count: 4
        particle_offset_x: 1
        particle_offset_y: 0.2
        particle_offset_z: 1
        particle: smoke_large
        orient: true
        orientPitch: false
  parameters:
    target: block
    target_type: Entity
    start_at_target: true
    x_size: 3
    y_size: 0
    z_size: 3
    size: 8
    range: 3
    allow_max_range: true
    orient: true
    target_count: 16
    item_speed: 0.4
    living_entity_speed: 0.6
    direction: 0,1,0
    speed: 0.8
    cooldown: 10000
    delay: 250
    brush: air
    falling: true
    undo: 15000
    damage: 6
    undo_speed: 0.5
  costs:
    mana: 70

#https://naruto.fandom.com/ru/wiki/Стихия_Земли:_Земляной_Вал
earthultimate:
  name: '[lang]magic.spells.basic.earth6.name[/lang]'
  description: '[lang]magic.spells.basic.earth6.description[/lang]'
  alias: earth6
  inherit: earth
  icon: diamond_pickaxe:28
  icon_disabled: diamond_axe:28
  worth: 60
  actions:
    cast:
    - class: DisablePhysics
    - class: Volume
      actions:
      - class: ModifyBlock
  effects:
    cast:
    - class: EffectSingle
      sound: entity_generic_splash
      location: both
    tick:
    - location: target
      particle: water_splash
      particle_count: 8
      particle_offset_x: 0.2
      particle_offset_y: 0.2
      particle_offset_z: 0.2
    hit:
    - class: EffectSingle
      location: target
      effectlib:
        class: Shield
        iterations: 10
        particle: water_splash
        radius: 1.8
        particles: 30
        particle_count: 20
        particle_offset_x: 0.2
        particle_offset_y: 0.2
        particle_offset_z: 0.2
  parameters:
    velocity: 250
    target_type: LivingEntity
    allow_max_range: true
    radius: 1
    range: 6
    cooldown: 2000
    undo: 30000
    duration: 3000
    destructible: destructible_replace
    brush: dirt:1
    hitbox: true
    x_size: 30
    y_size: 20
    z_size: 6
    volume_type: yxz
    orient: true
  costs:
    mana: 20